version: '3'

services:
        

        walletdata:
                image: mongo:latest
                ports:
                        - 27017-27019:27017-27019
        userdata:
                image: mongo:latest
                ports:
                        - 27017-27019:27017-27019

        wallet-api:
                image: bjsmiley/wallet.api
                build:
                        context: .
                        dockerfile: Services/Wallet/Wallet.API/Dockerfile
                depends_on:
                        - walletdata
                environment:
                        - ASPNETCORE_URLS=https://+;http://+
                        - ASPNETCORE_HTTPS_PORT=7001
                        - ASPNETCORE_Kestrel__Certificates__Default__Password=password123
                        - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/Wallet.API.pfx
                volumes:
                        - ${HOME}/.aspnet/https:/https/
                ports:
                        - 6901:80
                        - 7001:443

        user-api:
                image: bjsmiley/user.api
                build:
                        context: .
                        dockerfile: Services/Users/Users.API/Dockerfile
                depends_on:
                        - userdata
                        - wallet-api
                environment:
                        - ASPNETCORE_URLS=https://+;http://+
                        - ASPNETCORE_HTTPS_PORT=7002
                        - ASPNETCORE_Kestrel__Certificates__Default__Password=password123
                        - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/Users.API.pfx
                volumes:
                        - ${HOME}/.aspnet/https:/https/
                ports:
                        - 6902:80
                        - 7002:443


